version: '3.7'

services:
    db:
        image: postgres:12
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "secret"
            # POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - ./server/database.sql:/docker-entrypoint-initdb.d/001-init.sql
    api:
        build:
            context: ./server
        depends_on:
            - db
        environment:
            DB_USER: "admin"
            DB_PASSWORD: "secret"
            DB_HOST: db
            DB_PORT: 5432
        ports:
            - 5000:5000
    ui:
        build:
            context: ./client
        depends_on:
            - db
        environment:
            REACT_APP_SERVER_NAME: api
            REACT_APP_SERVER_PORT: 5000
        ports:
            - 3000:80
